# ─────────────────────────────────────────────────────────────────
#  api/main.py — OmniMind FastAPI REST Backend
#
#  WHY FASTAPI ALONGSIDE STREAMLIT?
#    Streamlit is great for interactive UIs but not for programmatic
#    access. A FastAPI backend lets other apps, scripts, or services
#    call OmniMind's features via standard REST API calls.
#
#  Run locally:
#    uvicorn api.main:app --reload --port 8000
#
#  Interactive docs (auto-generated by FastAPI):
#    http://localhost:8000/docs   ← Swagger UI
#    http://localhost:8000/redoc  ← ReDoc
# ─────────────────────────────────────────────────────────────────

import time
import io
from contextlib import asynccontextmanager

from fastapi import FastAPI, UploadFile, File, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image

from api.schemas import (
    ChatRequest, ChatResponse, SourceChunk,
    OCRResponse, DetectionResponse, Detection,
    VisualQARequest, VisualQAResponse,
    HealthResponse,
)
from mlflow_tracking.tracker import OmniMindTracker
from src.rag_chain import get_rag_chain, ask
from src.vision.ocr import extract_text
from src.vision.detection import detect_objects
from src.vision.visual_qa import ask_about_image


# ── Lifespan: load heavy resources once at startup ───────────────
# FastAPI's lifespan replaces the old @app.on_event("startup").
# We load the RAG chain once here so every request reuses it
# instead of rebuilding it on each call (which takes ~5 seconds).

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("[startup] Loading RAG chain...")
    app.state.rag_chain = get_rag_chain()
    app.state.tracker   = OmniMindTracker()
    print("[startup] Ready!")
    yield
    print("[shutdown] Cleaning up...")


# ── App setup ─────────────────────────────────────────────────────
app = FastAPI(
    title="OmniMind API",
    description="REST API for OmniMind — RAG chatbot + Computer Vision",
    version="1.0.0",
    lifespan=lifespan,
)

# Allow Streamlit (running on :8501) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Helper ────────────────────────────────────────────────────────
def get_chain():
    return app.state.rag_chain

def get_tracker():
    return app.state.tracker


# ════════════════════════════════════════════════════════════════
#  ROUTES
# ════════════════════════════════════════════════════════════════

@app.get("/", include_in_schema=False)
async def root():
    return {"message": "OmniMind API is running. Visit /docs for the API reference."}


# ── Health check ──────────────────────────────────────────────────
@app.get("/api/health", response_model=HealthResponse)
async def health():
    """
    Check which services are available.
    Useful for monitoring and CI/CD pipeline health gates.
    """
    import os
    return HealthResponse(
        status="ok",
        version="1.0.0",
        services={
            "rag_chain":    app.state.rag_chain is not None,
            "groq_key":     bool(os.getenv("GROQ_API_KEY")),
            "google_key":   bool(os.getenv("GOOGLE_API_KEY")),
        }
    )


# ── Chat (RAG) ────────────────────────────────────────────────────
@app.post("/api/chat", response_model=ChatResponse)
async def chat(
    request: ChatRequest,
    chain=Depends(get_chain),
    tracker=Depends(get_tracker),
):
    """
    Ask a question about loaded documents.
    Returns the answer + source citations + response time.
    """
    start = time.time()

    result  = ask(chain, request.question)
    elapsed = round((time.time() - start) * 1000, 2)

    # Format source chunks for the response
    sources = []
    for doc in result["sources"]:
        sources.append(SourceChunk(
            source  = doc.metadata.get("source", "Unknown"),
            page    = doc.metadata.get("page"),
            excerpt = doc.page_content[:300],
        ))

    # Log this experiment to MLflow
    tracker.log_chat(
        question      = request.question,
        answer        = result["answer"],
        source_count  = len(sources),
        response_time = elapsed,
    )

    return ChatResponse(
        answer          = result["answer"],
        sources         = sources,
        response_time_ms= elapsed,
    )


# ── Vision: OCR ───────────────────────────────────────────────────
@app.post("/api/vision/ocr", response_model=OCRResponse)
async def ocr(file: UploadFile = File(...)):
    """
    Extract text from an uploaded image using Tesseract OCR.
    Accepts: jpg, jpeg, png, webp, bmp
    """
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image")

    image_bytes = await file.read()
    image       = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    result      = extract_text(image)

    return OCRResponse(
        text       = result["text"],
        word_count = result["word_count"],
        confidence = result["confidence"],
    )


# ── Vision: Object Detection ──────────────────────────────────────
@app.post("/api/vision/detect", response_model=DetectionResponse)
async def detect(file: UploadFile = File(...)):
    """
    Detect objects in an uploaded image using YOLOv8 nano.
    Returns bounding boxes, labels, and confidence scores.
    """
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image")

    image_bytes = await file.read()
    image       = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    detections, _, summary = detect_objects(image)

    return DetectionResponse(
        detections   = [Detection(**d) for d in detections],
        summary      = summary,
        object_count = len(detections),
    )


# ── Vision: Visual Q&A ────────────────────────────────────────────
@app.post("/api/vision/qa", response_model=VisualQAResponse)
async def visual_qa(
    file: UploadFile = File(...),
    question: str    = "Describe this image in detail.",
):
    """
    Answer a question about an uploaded image using Gemini Flash.
    """
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image")

    image_bytes = await file.read()
    image       = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    result      = ask_about_image(image, question)

    return VisualQAResponse(
        answer   = result["answer"],
        question = result["question"],
        model    = result["model"],
    )
